server.port=8081
spring.datasource.url=jdbc:mysql://localhost:3306/playground_db
spring.datasource.username=root
spring.datasource.password=root

culqi.public-key=pk_test_xxxxxxxxxxxxx
culqi.secret-key=sk_test_xxxxxxxxxxxxx

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
